// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: internal/domain/proto/auto_market.proto

package grpc

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePublicationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brand          uint64 `protobuf:"varint,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Model          uint64 `protobuf:"varint,2,opt,name=model,proto3" json:"model,omitempty"`
	Vin            string `protobuf:"bytes,3,opt,name=vin,proto3" json:"vin,omitempty"`
	ProductionYear string `protobuf:"bytes,4,opt,name=production_year,json=productionYear,proto3" json:"production_year,omitempty"`
	Mileage        uint64 `protobuf:"varint,5,opt,name=mileage,proto3" json:"mileage,omitempty"`
	PicsCount      uint32 `protobuf:"varint,6,opt,name=pics_count,json=picsCount,proto3" json:"pics_count,omitempty"`
	OwnerCount     uint32 `protobuf:"varint,7,opt,name=owner_count,json=ownerCount,proto3" json:"owner_count,omitempty"`
}

func (x *CreatePublicationRequest) Reset() {
	*x = CreatePublicationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_domain_proto_auto_market_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePublicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePublicationRequest) ProtoMessage() {}

func (x *CreatePublicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_proto_auto_market_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePublicationRequest.ProtoReflect.Descriptor instead.
func (*CreatePublicationRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_proto_auto_market_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePublicationRequest) GetBrand() uint64 {
	if x != nil {
		return x.Brand
	}
	return 0
}

func (x *CreatePublicationRequest) GetModel() uint64 {
	if x != nil {
		return x.Model
	}
	return 0
}

func (x *CreatePublicationRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *CreatePublicationRequest) GetProductionYear() string {
	if x != nil {
		return x.ProductionYear
	}
	return ""
}

func (x *CreatePublicationRequest) GetMileage() uint64 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

func (x *CreatePublicationRequest) GetPicsCount() uint32 {
	if x != nil {
		return x.PicsCount
	}
	return 0
}

func (x *CreatePublicationRequest) GetOwnerCount() uint32 {
	if x != nil {
		return x.OwnerCount
	}
	return 0
}

type CreatePublicationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreatePublicationResponse) Reset() {
	*x = CreatePublicationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_domain_proto_auto_market_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePublicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePublicationResponse) ProtoMessage() {}

func (x *CreatePublicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_proto_auto_market_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePublicationResponse.ProtoReflect.Descriptor instead.
func (*CreatePublicationResponse) Descriptor() ([]byte, []int) {
	return file_internal_domain_proto_auto_market_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePublicationResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_internal_domain_proto_auto_market_proto protoreflect.FileDescriptor

var file_internal_domain_proto_auto_market_proto_rawDesc = []byte{
	0x0a, 0x27, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdb, 0x01, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76,
	0x69, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x79, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x65, 0x61, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x69, 0x6c, 0x65, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6d, 0x69,
	0x6c, 0x65, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x69, 0x63, 0x73, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x69, 0x63, 0x73, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2b, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x32, 0x78, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x6f, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x12, 0x6a, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x18, 0x3a, 0x01, 0x2a, 0x22, 0x13, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x08, 0x5a, 0x06,
	0x2e, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_domain_proto_auto_market_proto_rawDescOnce sync.Once
	file_internal_domain_proto_auto_market_proto_rawDescData = file_internal_domain_proto_auto_market_proto_rawDesc
)

func file_internal_domain_proto_auto_market_proto_rawDescGZIP() []byte {
	file_internal_domain_proto_auto_market_proto_rawDescOnce.Do(func() {
		file_internal_domain_proto_auto_market_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_domain_proto_auto_market_proto_rawDescData)
	})
	return file_internal_domain_proto_auto_market_proto_rawDescData
}

var file_internal_domain_proto_auto_market_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_domain_proto_auto_market_proto_goTypes = []interface{}{
	(*CreatePublicationRequest)(nil),  // 0: CreatePublicationRequest
	(*CreatePublicationResponse)(nil), // 1: CreatePublicationResponse
}
var file_internal_domain_proto_auto_market_proto_depIdxs = []int32{
	0, // 0: AutoMarket.CreatePublication:input_type -> CreatePublicationRequest
	1, // 1: AutoMarket.CreatePublication:output_type -> CreatePublicationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_domain_proto_auto_market_proto_init() }
func file_internal_domain_proto_auto_market_proto_init() {
	if File_internal_domain_proto_auto_market_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_domain_proto_auto_market_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePublicationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_domain_proto_auto_market_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePublicationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_domain_proto_auto_market_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_domain_proto_auto_market_proto_goTypes,
		DependencyIndexes: file_internal_domain_proto_auto_market_proto_depIdxs,
		MessageInfos:      file_internal_domain_proto_auto_market_proto_msgTypes,
	}.Build()
	File_internal_domain_proto_auto_market_proto = out.File
	file_internal_domain_proto_auto_market_proto_rawDesc = nil
	file_internal_domain_proto_auto_market_proto_goTypes = nil
	file_internal_domain_proto_auto_market_proto_depIdxs = nil
}
