name: Lint code

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          stable: 'false'
          go-version: '>=1.18.0'

      - name: lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh 
          | sh -s -- -b $(go env GOPATH)/bin 
          
          golangci-lint run
